Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/Void:
  Enabled: false # for Deferrable.+@
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  IgnoredPatterns:
  - http
  - ^[^'"]*/.+/
  - '%r'
Metrics/MethodLength:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  AllowedNames: [io, id, to, by, on, in, at, ip, db, it] # add 'it'
Style/AndOr:
  EnforcedStyle: conditionals
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FormatStringToken:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
Style/MultilineBlockChain:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/Not:
  Enabled: false
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
