Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  IgnoredPatterns:
  - http
  - ^[^'"]*/.+/
  - '%r'
Metrics/MethodLength:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FormatStringToken:
  EnforcedStyle: template
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
Style/MultilineBlockChain:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/Not:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
